In [1]:
from FantAIno.data.melondy_base import MelondyBaseDataset
from FantAIno.data.melondy_classic import MelondyClassicDataset
from FantAIno.utils.data_utils import process_melondy_genre

c:\Users\Owner\Documents\SillyProjects\FantAIno\FantAIno_venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
test = MelondyBaseDataset()

In [3]:
embeddings_df = test.retrieve_lyrics_embeddings()

In [4]:
album_data_df = test.retrieve_tabular_album_data()

In [5]:
embeddings_df.shape, album_data_df.shape

((3120, 1538), (3420, 15))

In [6]:
FantAIno_df = album_data_df.merge(embeddings_df, on=["album_name", "artist_name"], how="left")

In [7]:
FantAIno_df.head()

,artist_name,album_name,genre_list,rating,total_tracks,num_available_markets,release_year,release_month,release_day,album_duration_in_s,...,embedding_dim_1526,embedding_dim_1527,embedding_dim_1528,embedding_dim_1529,embedding_dim_1530,embedding_dim_1531,embedding_dim_1532,embedding_dim_1533,embedding_dim_1534,embedding_dim_1535
0,Various Artists,Pomegranates,[abstract hip hop],8,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.021058,0.035709,-0.005829,0.001882,-0.022754,0.023817,0.023164,-0.000509,0.026344,-0.008069
1,Tame Impala,Innerspeaker,"[psychedelic rock, neo-psychedelia]",6,11.0,184.0,2010.0,5.0,21.0,3201.461,...,-0.018038,0.017311,0.003317,0.010515,0.013309,0.026916,0.020972,0.015619,-0.004803,0.006878
2,Harlem,Hippies,"[garage rock, indie surf]",7,16.0,185.0,2010.0,4.0,5.0,2420.541,...,-0.034438,0.011370,0.016260,-0.006382,0.015454,0.018033,-0.008450,0.018540,0.000164,-0.006831
3,The Tallest Man on Earth,The Wild Hunt,"[contemporary folk, singer-songwriter]",8,10.0,185.0,2010.0,4.0,11.0,2082.361,...,-0.007364,0.018760,0.029363,-0.008673,0.003743,0.019907,-0.002858,0.019187,0.002696,-0.019762
4,Crystal Castles,Crystal Castles,"[synthpop, bitpop]",7,17.0,185.0,2008.0,3.0,18.0,3332.833,...,-0.009418,0.017512,0.010679,0.003541,-0.004204,0.038734,0.016807,0.002191,0.003354,-0.000092

In [8]:
FantAIno_df["rating"].unique()

array([ 8,  6,  7,  9,  3,  5,  4,  2, 10,  1, -1,  0, -2])

In [9]:
process_melondy_genre(FantAIno_df)

{'abstract hip hop': 141, 'psychedelic rock': 51, 'neo-psychedelia': 123, 'garage rock': 21, 'indie surf': 21, 'contemporary folk': 29, 'singer-songwriter': 198, 'synthpop': 95, 'bitpop': 4, 'stoner metal': 17, 'heavy metal': 19, 'avant-garde jazz': 13, 'jazz-rock': 5, 'noise pop': 29, 'indie rock': 218, 'indietronica': 66, 'dream pop': 38, 'indie pop': 110, 'idm': 28, 'black metal': 35, 'hardcore hip hop': 113, 'experimental hip hop': 116, 'conscious hip hop': 138, 'psychedelic pop': 48, 'hypnagogic pop': 7, 'alternative metal': 25, 'progressive electronic': 16, 'ambient': 28, 'proto-punk': 2, 'hard rock': 22, 'psychedelic soul': 13, 'electronic': 53, 'indie folk': 60, 'atmospheric black metal': 20, 'art pop': 210, 'blues rock': 16, 'opera': 2, 'experimental': 17, 'psychedelic folk': 9, 'slacker rock': 25, 'new wave': 17, 'new rave': 6, 'power pop': 25, 'contemporary r&b': 94, 'progressive soul': 22, 'experimental rock': 71, 'sludge metal': 24, "black 'n' roll": 5, 'synth punk': 11, 'krautrock': 4, 'dsbm': 1, 'pop rap': 230, 'electropop': 94, 'glitch hop': 21, 'wonky': 33, 'dance-punk': 14, 'alternative dance': 15, 'dance-punk revival': 13, 'drone': 15, 'comedy rap': 7, 'mashup': 8, 'cloud rap': 36, 'alt-pop': 95, 'balearic beat': 2, 'melodic black metal': 2, 'crust punk': 5, 'hardcore punk': 26, 'post-rock': 50, 'americana': 23, 'grindcore': 15, 'post-metal': 21, 'shoegaze': 19, 'post-punk': 75, 'occult rock': 10, 'garage rock revival': 12, 'post-punk revival': 18, 'folk rock': 16, 'art rock': 93, 'math rock': 18, 'math pop': 7, 'space rock': 1, 'boom bap': 54, 'chillwave': 9, 'mod revival': 1, 'dirty south': 4, 'chamber pop': 35, 'baroque pop': 11, 'country rock': 5, 'industrial hip hop': 24, 'traditional doom metal': 2, 'ambient americana': 2, 'boogie': 1, 'afro-funk': 5, 'baltimore club': 1, 'hip house': 4, 'downtempo': 10, 'plunderphonics': 6, 'avant-garde metal': 34, 'alternative rock': 103, 'alt-country': 11, 'alternative r&b': 136, 'witch house': 5, 'hip hop': 82, 'jangle pop': 10, 'bedroom pop': 22, 'punk blues': 5, 'twee pop': 9, 'post-dubstep': 20, 'geek rock': 7, 'chamber folk': 22, 'minimal wave': 2, 'synth funk': 12, 'doom metal': 14, 'brostep': 4, 'complextro': 1, 'metalcore': 27, 'instrumental hip hop': 15, 'garage psych': 15, 'noise rock': 60, 'sophisti-pop': 9, 'footwork': 5, 'uk bass': 19, 'nerdcore hip hop': 1, 'post-hardcore': 60, 'gothic rock': 11, 'future garage': 12, 'progressive folk': 10, 'microhouse': 5, 'doomgaze': 5, 'political hip hop': 17, 'minimal synth': 2, 'technical death metal': 15, 'dissonant death metal': 14, 'glitch pop': 31, 'funk': 7, 'jazz-funk': 5, 'deep funk': 1, 'ethio-jazz': 1, 'afro-jazz': 3, 'highlife': 1, 'afrobeat': 2, 'electro-disco': 5, 'funktronica': 5, 'pop soul': 22, 'avant-folk': 10, 'wyrd folk': 1, 'epic collage': 2, 'jazz rap': 46, 'southern rock': 3, 'roots rock': 4, 'cosmic country': 2, 'dance-pop': 45, 'folk pop': 14, 'pop rock': 84, 'sunshine pop': 3, 'nu-disco': 11, 'progressive metal': 28, 'electroacoustic': 5, 'drill and bass': 4, 'ambient pop': 19, 'trap': 271, 'industrial rock': 19, 'jazz fusion': 17, 'frat rap': 2, 'nu jazz': 12, 'dark ambient': 6, 'ambient dub': 5, 'stomp and holler': 3, 'a cappella': 1, 'choral': 1, 'polyphonic chant': 1, 'death doom metal': 3, 'atmospheric sludge metal': 13, 'darkwave': 10, 'powerviolence': 4, 'tech house': 10, 'uk garage': 4, 'deep tech': 1, 'deep house': 5, 'chicago drill': 5, 'gangsta rap': 64, 'garage punk': 16, "death 'n' roll": 2, 'chiptune': 2, 'post-industrial': 30, 'screamo': 13, 'dub': 1, 'blackgaze': 9, 'dub techno': 1, 'anti-folk': 7, 'dubstep': 3, 'punk rock': 11, 'mutant disco': 2, 'funeral doom metal': 1, 'death metal': 27, 'j-pop': 2, 'drumless': 26, 'progressive rock': 20, 'cumbia colombiana': 2, 'cumbia': 2, 'folktronica': 11, 'pigfuck': 6, 'mathcore': 10, 'digital hardcore': 5, 'art punk': 32, 'smooth soul': 4, 'ethereal wave': 4, 'pop': 38, 'disco': 5, 'emo': 15, 'pop punk': 22, 'dissonant black metal': 10, 'vocal jazz': 4, 'soul': 5, 'rhythm & blues': 2, 'electro house': 11, 'blackened crust': 1, 'neocrust': 1, 'death industrial': 5, 'neo-soul': 62, 'novelty': 1, 'musical parody': 4, 'deconstructed club': 13, 'noise': 4, 'industrial metal': 5, 'post-bop': 3, 'wonky techno': 1, 'french electro': 5, 'glitch': 5, 'progressive pop': 26, 'big beat': 2, 'house': 15, 'future bass': 8, 'trap [edm]': 10, 'gothic metal': 3, 'horror synth': 1, 'adult contemporary': 2, 'kawaii metal': 1, 'bubblegum bass': 11, 'folk metal': 1, 'pagan black metal': 1, 'country soul': 2, 'progressive country': 2, 'trip hop': 7, 'emo-pop': 3, 'glam rock': 6, 'grunge': 4, 'stoner rock': 6, 'mobb music': 1, 'musique concrète': 2, 'thrash metal': 14, 'grime': 6, 'electronic dance music': 31, 'midwest emo': 11, 'berlin school': 1, 'funky house': 2, 'heavy psych': 4, 'outlaw country': 1, 'contemporary country': 10, 'dreampunk': 1, 'electro-industrial': 17, 'shitgaze': 1, 'tape music': 3, 'emo rap': 23, 'film soundtrack': 5, 'hybrid trap': 5, 'spiritual jazz': 6, 'free improvisation': 1, 'k-pop': 5, 'soft rock': 7, 'ambient techno': 6, 'flamenco pop': 2, 'flamenco nuevo': 2, 'techno': 2, 'jazz poetry': 1, 'rap rock': 7, 'bro-country': 3, 'euro house': 1, 'diva house': 1, 'swancore': 2, 'horrorcore': 10, 'trap latino': 3, 'post-minimalism': 9, 'third stream': 2, 'heartland rock': 7, 'latin pop': 3, 'hyperpop': 11, 'mafioso rap': 13, 'power electronics': 1, 'drone metal': 9, 'musical comedy': 5, 'rage': 14, 'christian hip hop': 2, 'anatolian rock': 1, 'trap metal': 5, 'nouvelle chanson française': 1, 'chamber music': 5, 'avant-prog': 6, 'hard dance': 1, 'melodic death metal': 1, 'neue deutsche härte': 2, 'nashville sound': 1, 'shimokita-kei': 4, 'dance': 3, 'slowcore': 5, 'egg punk': 2, 'memphis rap': 4, 'country': 6, 'country pop': 5, 'uk drill': 1, 'funk metal': 1, 'digicore': 2, 'traditional pop': 3, 'sound collage': 6, 'vapor': 4, 'symphonic rock': 1, 'mexican folk music': 3, 'jerk': 2, 'trap soul': 4, 'brutal death metal': 3, 'poetry': 3, 'canción melódica': 1, 'zolo': 3, 'satire': 2, 'deathgrind': 5, 'futurepop': 2, 'afrobeats': 1, 'tropicália': 1, 'plugg': 2, 'american primitivism': 1, 'rock opera': 7, 'funk rock': 4, 'eurodance': 1, 'happy hardcore': 1, 'emoviolence': 2, 'aor': 2, 'futuristic swag': 1, 'classical crossover': 1, 'reggaetón': 4, 'caribbean music': 2, 'tecnofunk': 1, 'modern classical': 5, 'city pop': 1, 'street punk': 1, 'oi!': 1, 'new york drill': 1, 'ebm': 1, 'television music': 2, 'chamber jazz': 2, 'new age': 3, 'irish folk music': 1, 'symphonic prog': 2, 'boogie rock': 2, 'electroclash': 3, 'melodic house': 1, 'progressive house': 3, 'liquid drum and bass': 1, 'jungle': 1, 'tropicanibalismo': 4, 'synthwave': 1, 'piano rock': 3, 'latin alternative': 1, 'baggy': 1, 'detroit sound': 2, 'stutter house': 1, 'chipmunk soul': 4, 'jam band': 1, 'technical thrash metal': 3, 'soul blues': 1, 'hymns': 1, 'southern gospel': 1, 'zamrock': 1, 'totalism': 3, 'sample drill': 1, 'afroswing': 1, 'alté': 1, 'aggrotech': 1, 'electro': 3, 'vaporwave': 3, 'ska punk': 3, 'new tone': 3, 'nu metal': 3, 'third wave ska': 1, 'salsa': 1, 'latin electronic': 2, 'acid rock': 1, 'spirituals': 2, 'brutal prog': 1, 'neoperreo': 1, 'space rock revival': 1, 'europop': 1, 'ranchera': 2, 'bolero': 1, 'neoclassical darkwave': 5, 'progressive breaks': 1, 'chanson québécoise': 1, 'digital cumbia': 2, 'minimalism': 1, 'holy minimalism': 1, 'teen pop': 1, 'groove metal': 2, 'jungle terror': 1, 'glam punk': 1, 'breakcore': 2, 'rockabilly': 1, 'comedy rock': 2, 'soundtrack': 2, 'gothic country': 1, 'dark folk': 2, 'deathcore': 1, 'mpb': 1, 'jazz pop': 1, 'free jazz': 1, 'sass': 2, 'acid house': 2, 'worldbeat': 1, 'christmas music': 1, 'neofolk': 1, 'minneapolis sound': 1, 'modal jazz': 1, 'rock': 1, 'folk punk': 2, 'santería music': 1, 'dolewave': 2, 'american folk music': 1, 'britpop': 1, 'hyphy': 1, 'french house': 1, 'country folk': 1, 'ambient house': 1, 'nueva canción latinoamericana': 1, 'hispanic american folk music': 1, 'fusion gugak': 1, 'southern soul': 1, 'deep soul': 2, 'songo': 1, 'afro-cuban jazz': 1, 'crossover thrash': 3, 'symphonic black metal': 1, 'spoken word': 1, 'skate punk': 2, 'latin jazz': 1, 'war metal': 1, 'punk poetry': 1, 'industrial': 1, 'wave': 1, 'modern creative': 1, 'country rap': 1, 'drum and bass': 1, 'purple sound': 2, 'aquacrunk': 4, 'jazz': 3, 'outsider house': 1, 'acid techno': 1, 'midtempo bass': 1, 'melodic hardcore': 1, 'djent': 1, 'breakbeat': 1, 'minimal techno': 1, 'acoustic blues': 1, 'new orleans r&b': 1, 'surf punk': 1}
Genre must have been reviewed at least 34.2 times to be a categorical variable.
abstract hip hop                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103
alternative r&b         136
hip hop                  82
noise rock               60
post-hardcore            60
jazz rap                 46
dance-pop                45
pop rock                 84
trap                    271
gangsta rap              64
pop                      38
neo-soul                 62
psychedelic rock                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103
alternative r&b         136
hip hop                  82
noise rock               60
post-hardcore            60
jazz rap                 46
dance-pop                45
pop rock                 84
trap                    271
gangsta rap              64
pop                      38
neo-soul                 62
neo-psychedelia                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103
alternative r&b         136
hip hop                  82
noise rock               60
post-hardcore            60
jazz rap                 46
dance-pop                45
pop rock                 84
trap                    271
gangsta rap              64
pop                      38
neo-soul                 62
singer-songwriter                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103
alternative r&b         136
hip hop                  82
noise rock               60
post-hardcore            60
jazz rap                 46
dance-pop                45
pop rock                 84
trap                    271
gangsta rap              64
pop                      38
neo-soul                 62
synthpop                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103
alternative r&b         136
hip hop                  82
noise rock               60
post-hardcore            60
jazz rap                 46
dance-pop                45
pop rock                 84
trap                    271
gangsta rap              64
pop                      38
neo-soul                 62
indie rock                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103
alternative r&b         136
hip hop                  82
noise rock               60
post-hardcore            60
jazz rap                 46
dance-pop                45
pop rock                 84
trap                    271
gangsta rap              64
pop                      38
neo-soul                 62
indietronica                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103
alternative r&b         136
hip hop                  82
noise rock               60
post-hardcore            60
jazz rap                 46
dance-pop                45
pop rock                 84
trap                    271
gangsta rap              64
pop                      38
neo-soul                 62
dream pop                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103
alternative r&b         136
hip hop                  82
noise rock               60
post-hardcore            60
jazz rap                 46
dance-pop                45
pop rock                 84
trap                    271
gangsta rap              64
pop                      38
neo-soul                 62
indie pop                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103
alternative r&b         136
hip hop                  82
noise rock               60
post-hardcore            60
jazz rap                 46
dance-pop                45
pop rock                 84
trap                    271
gangsta rap              64
pop                      38
neo-soul                 62
black metal                       count
abstract hip hop        141
psychedelic rock         51
neo-psychedelia         123
singer-songwriter       198
synthpop                 95
indie rock              218
indietronica             66
dream pop                38
indie pop               110
black metal              35
hardcore hip hop        113
experimental hip hop    116
conscious hip hop       138
psychedelic pop          48
electronic               53
indie folk               60
art pop                 210
contemporary r&b         94
experimental rock        71
pop rap                 230
electropop               94
cloud rap                36
alt-pop                  95
post-rock                50
post-punk                75
art rock                 93
boom bap                 54
chamber pop              35
alternative rock        103

,artist_name,album_name,rating,total_tracks,num_available_markets,release_year,release_month,release_day,album_duration_in_s,explicit_proportion,...,is_hip hop,is_noise rock,is_post-hardcore,is_jazz rap,is_dance-pop,is_pop rock,is_trap,is_gangsta rap,is_pop,is_neo-soul
0,Various Artists,Pomegranates,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
1,Tame Impala,Innerspeaker,6,11.0,184.0,2010.0,5.0,21.0,3201.461,0.000000,...,False,False,False,False,False,False,False,False,False,False
2,Harlem,Hippies,7,16.0,185.0,2010.0,4.0,5.0,2420.541,0.000000,...,False,False,False,False,False,False,False,False,False,False
3,The Tallest Man on Earth,The Wild Hunt,8,10.0,185.0,2010.0,4.0,11.0,2082.361,0.000000,...,False,False,False,False,False,False,False,False,False,False
4,Crystal Castles,Crystal Castles,7,17.0,185.0,2008.0,3.0,18.0,3332.833,0.176471,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,Battles,Gloss Drop,9,12.0,185.0,2011.0,6.0,6.0,3233.745,0.000000,...,False,False,False,False,False,False,False,False,False,False
3416,Colin Stetson,"New History Warfare, Volume 2: Judges",8,14.0,184.0,2011.0,2.0,22.0,2681.235,0.000000,...,False,False,False,False,False,False,False,False,False,False
3417,Wavves,King of the Beach,8,12.0,185.0,2010.0,NaN,NaN,2219.009,0.250000,...,False,False,False,False,False,False,False,False,False,False
3418,Foals,Total Life Forever,4,27.0,180.0,2010.0,5.0,7.0,5119.844,0.000000,...,False,False,False,False,False,False,False,False,False,False
3419,The Drums,The Drums,8,12.0,184.0,2010.0,6.0,7.0,2595.130,0.000000,...,False,False,False,False,False,False,False,False,False,False